# Solver selection: supports cplex, gurobi
solver.name=gurobi

# Time limits (seconds)
solver.timelimit=3600

# Thread settings: default 0 (the solver keeps the setting at default)
solver.threads=0

# MIP parameters
#to be added...

# Logging
# separate logging will create a log file for each instance
# otherwise, a single log file (named solver.logfile) will be maintained
solver.log=false
solver.console=true
solver.separateLog=true
solver.solution=true
solver.logfile=logfile.log
solver.logpath=logs/solver/
solver.solpath=solutions/solver/